### ISSUE TITLE
https + rtmps

### ISSUE THREAD

**Issue by rallep71** [TareqAlqutami/rtmp-hls-server#11]
Hallo,

is there a possibility to integrate letsencrypt for https and rtmps into the docker image?
See here for an example:
https://serverfault.com/questions/1019317/receiving-rtmps-stream-on-nginx-rtmp

thx

**Comment by TareqAlqutami** [comment]
Hello @rallep71,
I believe it is possible. This requires some efforts to modify the current codebase. 
Would you be interested to submit a pull request for that?
It is one of the things I wish to add but it would not happen in the near future given my current limited state of knowledge on this.

Thanks

**Comment by JamiePhonic** [comment]
If it's of any use, i already forked your repo a while back and added RTMPS support for facebook live for a project i was working on. It should be easy enough to tweak the configurations to allow it to recieve an RTMPS stream.

I also modified the container to auto populate a directory with the config and player files on first run so that you only need to map a single directory on your host rather than passing individual files.
https://github.com/JamiePhonic/rtmp-hls-stunnel-server
(i also bumped the nginx and ffmpeg versions to the latest stable at the time)

For ssl support on the players, i would recommend a reverse proxy setup through something like NginxProxyManager, HAProxy, or just another NginX instance.
