### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by fabltd** [TareqAlqutami/rtmp-hls-server#29]
Hi

Has somthing changed. I have tried two machines (Both Macs) running this. Whilst OBS seems to think its streaming to the server there is no output.

Any troubleshooting you would suggest?

Thanks

JT

**Comment by TareqAlqutami** [comment]
Hello @fabltd 
I have just tested the latest docker image and it seems to work. I tested in Linux Ubunutu since I don't have Mac.
It would be helpful if you can share more info such as the docker logs, which command was used to run the image, how do you play the stream, and what the stats (http://localhost:8080/stats) page shows.

**Comment by SimonRijn** [comment]
@TareqAlqutam i Have the same here.

Below a screenshot of my stats
![image](https://user-images.githubusercontent.com/20671637/159521659-c8c8097a-5313-4b58-853a-f21efb17e9b0.png)

Screenshot of Docker logs: (Seems like there is an error with renaming the HLS file but don't think this is the issue)
![image](https://user-images.githubusercontent.com/20671637/159522860-cfeabae7-67fe-4bea-b429-abed840cc5ec.png)

I run the image in rancher but that shouldn't matter in principle

VLC sees that there is a stream and also indicates the correct time, with a delay of 20 seconds, but only get a black screen
![image](https://user-images.githubusercontent.com/20671637/159524315-8b0d7379-38a7-44c3-a04d-206034841ea4.png)

**Comment by SimonRijn** [comment]
![image](https://user-images.githubusercontent.com/20671637/159684593-6f693863-471f-4bfb-af3f-de31678f138d.png)
Above is a screenshot of the stats page which shows that there is a connection but via VLC I get a black screen. VLC does seem to have a connection

EDIT: 
It seems like I get some sound from the stream

I suspect it's my OBS. If I want to stream via, for example, my DJI app, it works.

**Comment by TareqAlqutami** [comment]
@SimonRijn  so in your case, no issue with the server?

**Comment by otterstedt** [comment]
I have the same issue, black screen with sound. The ffmpeg process that pushes the rtmp shows both audio/video.
And it is like above on the stats page 0kb/s on video and >0 on sound while the row next to test has value for video

It seems intermittent.

I have restarted the container and then sometimes the video comes back again.

Could it be some state that gets messed up inside and the video breaks?

I am playing around a lot but the same ffmpeg command creating the stream sometimes gets video and sometimes not.

Is it possible to disable the adaptive streaming?

**Comment by TareqAlqutami** [comment]
@otterstedt can you share the details of your setup: 
- Your nginx config
- Command you used to run the docker image
- How do you visualize the stream (VLC) and which protocol (RTMP, HLS,..)

You can modify the ffmpeg command and adaptive streaming options in the nginx config.

Moreover, did you test the streaming using a different video, webcam to ensure it is not the video itself causing the issue?

**Comment by otterstedt** [comment]
@TareqAlqutami I am using the vanilla docker, no modifications to the image/container. So I have not even had a peek on the config.

It happens intermittently for the same collection of video files. Same video works one time, next time it is black.

I am using the built in hls web player.
The video has bit/s value on the 'test' row, but in the "adaptive streams section" it is 0, just like in the above screenshot. 

It seems it is the conversion from incoming rtmp to the adaptive streams that drops the video.
If I open the rtmp stream: rtmp://<server ip>:1935/live/test with VLC I get video and sound
If I open the HLS with the player at: http://<server ip>::8080/players/hls.html I get just sound
If I open the HLS stream: http://<server ip>:8080/hls/test.m3u8 with VLC I get just sound

which I guess make sense as the stats page indicates value for video on the 'test' row, while it has 0 in the "shows" section

I am very much a newbie to video streaming, but just wanted to give some input as I face the same issue. Hopefully it can give some leads :)

**Comment by TareqAlqutami** [comment]
I tried to replicate but I didn't get the same results. It might be due to ffmpeg crashing and if that happens it might be due to the video! since rtmp stream is always OK but the adaptive streams are the one affected.

You can confirm that ffmpeg is generating the streams by looking at the produced HLS/dash files
- execute into the container `docker exec -it <container-name> bash`
-  cd into the directories within `/mnt`.  `cd /mnt/hls`
- The directory is empty and gets populated when adaptive streaming is working:
![image](https://user-images.githubusercontent.com/46659456/160746199-4ebe9fc4-3c7f-487f-b1af-cf663182c020.png)

Another check is to look into the container log if there are any reports of process exiting
```
docker logs -f <container-name>
```
For example when I stopped streaming, I saw the process exited and all adaptive streams stopped.
![image](https://user-images.githubusercontent.com/46659456/160746571-c9548e5f-d4d1-4271-a826-a785cd10fd90.png)
